export const categories = [
    {key: "9", topic: "General Knowledge"},
    {key: "17", topic: "Science & Nature"},
    {key: "27", topic: "Animals"},
    {key: "18", topic: "Computers"},
    {key: "19", topic: "Mathematics"},
    {key: "22", topic: "Geography"},
    {key: "24", topic: "Politics"},
    {key: "23", topic: "History"},
    {key: "20", topic: "Mythology"}, 
    {key: "25", topic: "Art"},
    {key: "21", topic: "Sports"},
    {key: "26", topic: "Celebrities"},
    {key: "28", topic: "Vehicles"},
    {key: "30", topic: "Gadgets"},
    {key: "10", topic: "Books"},
    {key: "29", topic: "Comics"},
    {key: "31", topic: "Anime & Manga"},
    {key: "32", topic: "Cartoon & Animation"},
    {key: "11", topic: "Film"},
    {key: "12", topic: "Music"},
    {key: "13", topic: "Musicals & Theatres"},
    {key: "14", topic: "Television"},
    {key: "15", topic: "Video Games"},
    {key: "16", topic: "Board Games"}
]